### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'data'

### ISSUE THREAD

**Issue by zoeyhaiyan1** [czhaneva/MST-GCN#5]
跑到51个epoch报错
AttributeError: 'tuple' object has no attribute 'data'
是什么原因呢

**Comment by czhaneva** [comment]
把完整的日志贴一下

**Comment by zoeyhaiyan1** [comment]
Traceback (most recent call last):
  File "main.py", line 621, in <module>
    processor.start()
  File "main.py", line 562, in start
    loader_name=['test'])
  File "main.py", line 491, in eval
    _, predict_label = torch.max(output.data, 1)
AttributeError: 'tuple' object has no attribute 'data'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 244) of binary: /root/miniconda3/envs/MST-GCN/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/MST-GCN/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/envs/MST-GCN/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/MST-GCN/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/root/miniconda3/envs/MST-GCN/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/root/miniconda3/envs/MST-GCN/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/root/miniconda3/envs/MST-GCN/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/root/miniconda3/envs/MST-GCN/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/MST-GCN/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-06_03:42:35
  host      : autodl-container-6f1911bc52-91ea5c32
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 244)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by zoeyhaiyan1** [comment]
Traceback (most recent call last):
  File "main.py", line 621, in <module>
    processor.start()
  File "main.py", line 562, in start
    loader_name=['test'])
  File "main.py", line 491, in eval
    _, predict_label = torch.max(output.data, 1)
AttributeError: 'tuple' object has no attribute 'data'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 244) of binary: /root/miniconda3/envs/MST-GCN/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/MST-GCN/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/envs/MST-GCN/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/MST-GCN/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/root/miniconda3/envs/MST-GCN/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/root/miniconda3/envs/MST-GCN/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/root/miniconda3/envs/MST-GCN/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/root/miniconda3/envs/MST-GCN/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/MST-GCN/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------

**Comment by fywwy** [comment]
> 跑到51个epoch报错 AttributeError: 'tuple' object has no attribute 'data' 是什么原因呢
我也遇到了这个问题

**Comment by czhaneva** [comment]
我不太清楚造成这个的原因的是什么，但我觉得你们可以进入debug模式（1. 采用少量数据训练 或者2. 直接将初始epoch设置为50）， 然后在491行之后的debug一下，查看下output的格式或者shape，然后对应修改代码即可
